name: Lint

on:
    push:
        branches:
            - master
        tags-ignore:
            - "**"
    pull_request: null

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        strategy:
            fail-fast: false
            matrix:
                host:
                    - macos-latest
                    - windows-latest
                    - ubuntu-latest
        name: Lint on ${{ matrix.host }}
        runs-on: ${{ matrix.host }}
        steps:
            - uses: actions/checkout@v3

            - name: Install rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  components: rustfmt, clippy

            - name: Cargo fmt
              run: cargo fmt -- --check

            - name: Clippy
              run: cargo clippy

            - name: Test
              run: cargo test
    publish:
        name: Publish
        runs-on: ubuntu-latest
        needs:
            - lint
        steps:
            - uses: actions/checkout@v3

            - name: Install rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  components: rustfmt, clippy

            - name: Publish
              if: github.event_name != 'pull_request'
              env:
                  CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
              run: cargo publish --registry crates-io --token $NPM_TOKEN
